### ISSUE TITLE
Plus (+) symbol in URL query strings.

### ISSUE THREAD

**Issue by drekka** [hummingbird-project/hummingbird#141]
Hi

Just been looking at the use of the "+" symbol to represent a space in URLs. There's a lot of long winded discussions on the topic around the inter webs but I got the impression that its value as a representative of a space in a URL's query arguments. So something like this:

```
https://127.0.0.1/8080/abc?a1=Hello+World
```

As opposed to percent encoding:

```
https://127.0.0.1/8080/abc?a1=Hello%20World
```

I'm playing around with this and either I've done something wrong or Hummingbird doesn't appear to handle '+' space characters. I'm looking at `URL.swift`'s extension to `HBParameters` on line 155 where it says

```swift
return (key: key.string[...], value: value.percentDecode().map { $0[...] } ?? value.string[...])
```

I'm wondering if this should also handle the '+' symbol. like this:

```swift
return (key: key.string[...], value: value. replacingOccurrences(of:"+", with: "%20").percentDecode().map { $0[...] } ?? value.string[...])
```

Just a guess.

**Comment by adam-fowler** [comment]
Hey there
Sorry took so long to respond. The [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) does not include encoding spaces with a `+` sign. It suggests they should be percent encoded `%20`. There is some suggestion that query values should be encoded as `application/x-www-form-urlencoded` which does include a `+` encoding for spaces. I would prefer to stick to `%20` for now simply because it means we need to do less processing of query values.

**Comment by drekka** [comment]
Yeah, works for me, I'll let you know if I hit any problems with this as I don't control the URLs :-)
