### ISSUE TITLE
Hook to customize creation of Request Context

### ISSUE THREAD

**Issue by davedelong** [hummingbird-project/hummingbird#419]
I want to provide a context to my request handlers that has properties for ancillary services, like database connections or other storage mechanisms.

However, the contexts have to conform to a protocol with a required initializer, which means I do not get a chance to proactively populate the context myself before it shows up in the request handling chain. I could add some optional properties (or even implicitly unwrapped optionals) to the context and then add a middleware just to populate them, but it feels "cleaner" to have a hook on the `Router` that is a `(Channel, Logger) -> Context` closure. That way I could construct the context myself with all the necessary connections I know I'm going to need.

This would have the added benefit of removing the need of the initializer on the `RequestContext` protocol, perhaps resulting in the elimination of that protocol entirely (or keeping it around as a convenience, and not a requirement).

**Comment by adam-fowler** [comment]
The Application creates the Context so the hook would be there. It should be possible to create an Application `init` which takes a Context conforming to just `BaseRequestContext` which doesn't require the init. I would imagine I would keep the protocol RequestContext still just so I can setup defaults for request contexts.

As an aside it is not very efficient setting up a bunch of member variables on a context for every request. When instead you could pass those variables to routes via closure capture.

eg
```swift
let database = Database()
router.get { request, context in
    database.get()
}
```
instead of
```swift
let database = Database()
let router = Router {
    // called for every request
    return MyContext(database)
}
router.get { request, context in
    context.database.get()
}
```
