### ISSUE TITLE
Investigate confusing router API

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird#445]
Adding a middleware to the router only affects routes defined _after_ the middleware was added. I believe this to be confusing behaviour, and believe we should investigate the API design here.

**Comment by adam-fowler** [comment]
This happens because the current middleware chain is applied at the point the route is added. I actually think this correct. It also provides flexibility in that someone can add middleware, some routes and then add some more middleware that won't be applied to the existing routes. Anyway if we were to stick with this it have to be documented for sure.

**Comment by adam-fowler** [comment]
Added documentation. I think this makes sense as is. It is just different to Vapor, so people might have expectations.
Given you can use the builder pattern, to construct your router it doesn't really make sense to have middleware applied to already added routes
```swift
router
    .get("/user", use: GetUsers)
    .add(middleware: MyMiddleware()
```
In the above example it doesn't make sense to apply `MyMiddleware` to the GET /user endpoint
